function renderImagesWithCaptions(imageArray) {
    const container = document.createElement('div');
    container.className = 'image-container';
    imageArray.forEach(imageObj => {
        const imgElement = document.createElement('img');
        imgElement.src = imageObj.url;
        const captionElement = document.createElement('p');
        captionElement.textContent = imageObj.caption;
        const wrapper = document.createElement('div');
        wrapper.className = 'image-wrapper';
        wrapper.appendChild(imgElement);
        wrapper.appendChild(captionElement);
        container.appendChild(wrapper);
    });
    return container;
}
const imagesWithCaptions = [
    { url: 'https://n3vesl1s.github.io/dict/images/gallery/lywjk9b3a2qc1_1.png', 
        caption: 'Кафиф' },
    { url: 'https://n3vesl1s.github.io/dict/images/gallery/1202291472229994506.webp', 
        caption: 'Пися'},
    { url: 'https://n3vesl1s.github.io/dict/images/gallery/generation.png', 
        caption: 'Furstur' },
    { url: 'https://n3vesl1s.github.io/dict/images/gallery/IMG20231126145500.png', 
        caption: 'Кот Ghiggi' },
    { url: 'https://n3vesl1s.github.io/dict/images/gallery/IMG_6180.jpg', 
        caption: 'Youngbomb'},
    { url: 'https://n3vesl1s.github.io/dict/images/gallery/IMG_20240131_084803-1.jpg', 
        caption: 'Angrybomb'},
    { url: 'https://n3vesl1s.github.io/dict/images/gallery/7ad6464d8c48bd340b0ddbdc99314383.png', 
        caption: 'Miofif'},
    { url: 'https://n3vesl1s.github.io/dict/images/gallery/image0.jpg', 
        caption: 'Это DenisC'},
    { url: 'https://n3vesl1s.github.io/dict/images/gallery/bruh-6.jpg', 
        caption: 'looks cool (FurryC)'},      
    { url: 'https://n3vesl1s.github.io/dict/images/gallery/104_20230702102242.png', 
        caption: 'I am horny! (Miobomb)'},
    { url: 'https://n3vesl1s.github.io/dict/images/gallery/IMG_4767.jpg', 
        caption: 'я теперь фуре! (Nosleep)'},
    { url: 'https://n3vesl1s.github.io/dict/images/gallery/235_20240214123654.png', 
        caption: "Ава миобомба"},
    { url: 'https://n3vesl1s.github.io/dict/images/gallery/78_20240607203549.png', 
        caption: 'I feel so фура! (Vustur)'}, 
    { url: 'https://n3vesl1s.github.io/dict/images/gallery/68_20240524214835.png', 
        caption: 'Фура стафф'},
    { url: 'https://n3vesl1s.github.io/dict/images/gallery/54_20240511221346.png', 
        caption: 'Фото миобомба с фильтром'},
    { url: 'https://n3vesl1s.github.io/dict/images/gallery/47_20240509225649.png', 
        caption: 'Foxtur'},
    { url: 'https://n3vesl1s.github.io/dict/images/gallery/Screenshot_2024-02-21-20-39-36-78_572064f74bd5f9fa804b05334aa4f912.jpg', 
        caption: 'Kerfus'},
    { url: 'https://n3vesl1s.github.io/dict/images/gallery/Screenshot_2024-02-24-16-36-31-36_99c04817c0de5652397fc8b56c3b3817.jpg', 
        caption: 'Happybomb'},
    { url: 'https://n3vesl1s.github.io/dict/images/gallery/Screenshot_2024-05-16-00-22-01-70_572064f74bd5f9fa804b05334aa4f912.jpg', 
        caption: 'Ролить соль (Nosleep)'},
    { url: 'https://n3vesl1s.github.io/dict/images/gallery/image1.jpg', 
        caption: 'Rekafif или Kafif'},
    { url: 'https://n3vesl1s.github.io/dict/images/gallery/image2.jpg',
        caption: 'Fif issue'},
    { url: 'https://n3vesl1s.github.io/dict/images/gallery/Screenshot_956.png',
        caption: 'Kerfusbomb'},
    { url: 'https://n3vesl1s.github.io/dict/images/gallery/4ce3e7e0a9396c7931495d504121a027.png', 
        caption: 'Nosleep'},
    { url: 'https://n3vesl1s.github.io/dict/images/gallery/1108024359160918056.webp', 
        caption: 'Rekafif'},
    { url: 'https://ibb.co/R4xGS21',
        caption: 'Шаурма'},
    { url: 'https://ibb.co/D7prfjQ',
         caption: 'Аргумент'},
     { url: 'https://ibb.co/gZbr1YC', 
         caption: 'Putinbomb'},
     { url: 'https://ibb.co/6sKMd1D',
         caption: 'Фура хелпер'},
     { url: 'https://ibb.co/9YfZwrp',
         caption: 'Аж под аж ож об the morning will be great'},
     { url: 'https://ibb.co/VpWw0Wn',
         caption: 'Фураслип отправляет стикер'},
      { url: 'https://ibb.co/Cn4WgzS', 
         caption: 'Мио Зеленский'},
      { url: 'https://ibb.co/1dfZVDS', 
         caption: 'Фафиф торт'},
      { url: 'https://ibb.co/jf95D2Q', 
         caption: 'Миобомб с обращения'},
      { url: 'https://ibb.co/yg5TKSZ', 
         caption: 'ДенисЦ орёт на ФурриЦ'},
      { url: 'https://ibb.co/XVNG3Dr', 
         caption: 'Пушистый и ноутбук с миобомбом'},
      { url: 'https://ibb.co/cY2d0jY', 
         caption: 'Кафиф зевает ирл'},
      { url: 'https://ibb.co/yXfWFYD', 
         caption: 'Нарисованная иконка копирования'},
      { url: '', 
         caption: 'Миобомб и миобомб и миобомб...'},
      { url: 'https://ibb.co/Yt7Ppxy', 
         caption: 'Аж под об the morning😏🤫'},
      { url: 'https://ibb.co/d5GfwcV', 
         caption: 'Фифляндия'},
      { url: 'https://ibb.co/7X9Rr4X', 
         caption: 'Хитрый миобомб'},
      { url: 'https://ibb.co/X49H2K9', 
         caption: 'Zombiebomb'},
      { url: 'https://ibb.co/fdkDYrM', 
         caption: 'Очень злой миобомб'},
      { url: 'https://cdn.discordapp.com/attachments/1253263045552242739/1253671138505134161/d1kVAw9.png?ex=6676b3bb&is=6675623b&hm=64d80f7af260fdda28766e509b637dee2ed28e4a0f41de8c89788a0079330f0c&', 
         caption: 'Успех кафифа'},
      { url: 'https://ibb.co/cJpnh1B', 
         caption: 'Фура рекафиф и его семья'},
      { url: 'https://cdn.discordapp.com/attachments/1253263045552242739/1253713691321569371/ogMpQOvoIw.png?ex=6677841c&is=6676329c&hm=74c259e9253c1a37b2d6b8b25b0c566b2eb9bf030213bc8c2c20cb6e9c566fba&', 
         caption: 'Миньонбомб'},
      { url: 'https://ibb.co/GCzFMCz', 
         caption: 'Довольный миобомб'},
      { url: 'https://ibb.co/2sNvvyM', 
         caption: 'miobomb noob'},
      { url: 'https://ibb.co/7bNQFff', 
         caption: 'Rekafif is a right guy'},
      { url: 'https://ibb.co/cwcbwzT', 
         caption: 'Арт пивозавра'},
      { url: 'https://ibb.co/nnPk4fS', 
         caption: 'Quadrofif'},
      { url: 'https://ibb.co/BCfXTg8', 
         caption: 'Огромный капибомб'},
      { url: 'https://ibb.co/r3ZSqQN', 
         caption: 'Осабомб'},
      { url: 'https://ibb.co/ZGyqH5G', 
         caption: 'Довольный маньяк мио'},
      { url: 'https://ibb.co/tmvRhcv', 
         caption: 'Свинарник в форме авы DenisC'},
      { url: 'https://ibb.co/gjMn0XD', 
         caption: 'Оксана ghiggi снова'},
];
document.body.appendChild(renderImagesWithCaptions(imagesWithCaptions));

// { url: '', 
//     caption: ''},
